export { MainPage } from "./main"
export { RegisterPage } from "./register"
export { CreateTheTeamPage } from "./create-the-team"
export { JoinPage } from "./join"
export { TeamPage } from "./team"
export { ProjectPage } from "./project"